// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID               int64          `json:"id"`
	CreatedAt        time.Time      `json:"created_at"`
	ToolName         string         `json:"tool_name"`
	IpAddress        string         `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	InputSizeBytes   sql.NullInt64  `json:"input_size_bytes"`
	OutputSizeBytes  sql.NullInt64  `json:"output_size_bytes"`
	ProcessingTimeMs sql.NullInt64  `json:"processing_time_ms"`
	Status           string         `json:"status"`
	ErrorMessage     sql.NullString `json:"error_message"`
}
