// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package tools

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/tmunongo/nanotools/web/templates"
)

func Base64Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"tool-page\"><div class=\"tool-header\"><div class=\"tool-icon\">🔐</div><h2>Base64 Encoder & Decoder</h2><p class=\"tool-description\">Convert between text and Base64 encoding. Perfect for data URIs, API tokens, and embedded content.</p></div><div class=\"tool-content\"><!-- Encoding Section --><div class=\"tool-form\"><h3 class=\"section-title\">Encode to Base64</h3><form hx-post=\"/api/tools/base64/encode\" hx-target=\"#encode-output\" class=\"base64-form\"><div class=\"form-section\"><label for=\"encode-input\" class=\"form-label\"><span class=\"label-dot\"></span> Text to encode</label> <textarea id=\"encode-input\" name=\"input\" class=\"json-textarea\" placeholder=\"Enter text to encode...\" rows=\"8\" required></textarea></div><div class=\"form-actions\"><button type=\"submit\" class=\"btn btn-primary btn-full\">Encode to Base64</button></div></form><div id=\"encode-output\" class=\"output-preview\"><div class=\"empty-state\"><p>Base64 output will appear here</p></div></div></div><!-- Decoding Section --><div class=\"tool-form\"><h3 class=\"section-title\">Decode from Base64</h3><form hx-post=\"/api/tools/base64/decode\" hx-target=\"#decode-output\" class=\"base64-form\"><div class=\"form-section\"><label for=\"decode-input\" class=\"form-label\"><span class=\"label-dot\"></span> Base64 to decode</label> <textarea id=\"decode-input\" name=\"input\" class=\"json-textarea\" placeholder=\"Enter Base64 to decode...\" rows=\"8\" required></textarea></div><div class=\"form-actions\"><button type=\"submit\" class=\"btn-primary btn-full\">Decode from Base64</button></div></form><div id=\"decode-output\" class=\"output-preview\"><div class=\"empty-state\"><p>Decoded output will appear here</p></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Layout("Base64 Encoder/Decoder").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
