// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package tools

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/tmunongo/nanotools/web/templates"
)

func JSONFormatterPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"tool-page\"><div class=\"tool-header\"><div class=\"tool-icon\">📝</div><h2>JSON Formatter & Validator</h2><p class=\"tool-description\">Format, validate, and beautify your JSON. Instant feedback with syntax highlighting.</p></div><div class=\"tool-content\"><form hx-post=\"/api/tools/json-format\" hx-target=\"#json-output\" hx-trigger=\"input changed delay:500ms from:#json-input\" class=\"tool-form\"><div class=\"form-section\"><label for=\"json-input\" class=\"form-label\"><span class=\"label-dot\"></span> Paste your JSON</label> <textarea id=\"json-input\" name=\"input\" class=\"json-textarea\" placeholder='{\"message\": \"Paste JSON here...\"}' rows=\"12\"></textarea></div><div class=\"form-section\"><label class=\"form-label\"><span class=\"label-dot\"></span> Formatting options</label><div class=\"options-grid\"><label class=\"option-label\"><input type=\"number\" name=\"indent\" value=\"2\" min=\"0\" max=\"8\" class=\"indent-input\"> <span>Indent spaces</span></label> <label class=\"option-label\"><input type=\"checkbox\" name=\"sort_keys\" class=\"checkbox\"> <span>Sort keys alphabetically</span></label></div></div><div class=\"form-actions\"><button type=\"submit\" class=\"btn-primary\">Format JSON</button></div></form><div id=\"json-output\" class=\"output-section\"><div class=\"empty-state\"><p>Formatted JSON will appear here</p></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Layout("JSON Formatter").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
